### ISSUE TITLE
constant CPU usage

### ISSUE THREAD

**Issue by auronandace** [maverik-io/musicman#3]
Really nice project. The `0.1.3` release now works for me and finds my music files to add. The command based approach is quite different to what I'm used to for a music player but I'm liking it so far. Nice work!

I like to use `btm` (https://github.com/ClementTsang/bottom) to monitor resource usage. While `musicman` is running it is constantly using up a CPU core even when idle waiting for a command and not playing music. Are you using some sort of busy loop?

**Comment by mavenried** [comment]
Yup, there is are 2 threads running, one gets the commands and the other is just a loop that handles playback.
I am new to concurrency in general. Do you have any suggestions to fix this one?

**Comment by auronandace** [comment]
I think I see where you are busy looping. In your `utils/mod.rs` file you are matching on `try_recv()` in your loop. You'll want to change that to `recv()`.

The general principle is that you want each thread to be blocking. That way a thread only does work when it needs to. It seems the `rodio` library creates a separate audio thread so you shouldn't have to worry about sound not working while your loop is waiting for input from your other thread.

**Comment by mavenried** [comment]
The problem with this is that i have a custom queue implementation (not using the rodio one as i need to show which one is playing and stuff), and the busy loop in question was what handled the skipping to the next song when the current one was done.

**Comment by mavenried** [comment]
if you have any ideas, a pr would be welcome :)

**Comment by auronandace** [comment]
In that case you probably want some sort of message passing system. When a song is finished playing send a message that then begins the playing of the next song in the queue. You may need to involve another thread.

The important thing is to avoid a busy loop. All threads should be blocking on something (waiting for a message from one of the other threads and sending a message when its work is done).

**Comment by mavenried** [comment]
I'm sorry to ask but could you recommend a good resource for this, even better, could you try fixing this yourself and PR'ing? i'd like to know how to have better handled this...

**Comment by auronandace** [comment]
I've tried taking a look through it and I can't find a clean way to work around the issue and keep your current structure reasonably unchanged.

If I were to fix the issue it would effectively be a rewrite from scratch. This is because of the way you have your `init` function handling both the incoming user input and relying on the `Err` case to handle loading the next song in the queue. That loop is calling the `Err` case thousands of times a second which is a complete waste of CPU cycles, the busy loop.

The approach I would probably take would involve 3 different threads:
- one that blocks on user input (a sender)
- one that blocks on messages (this would be the main thread waiting on the other 2, a sender and receiver)
- one that blocks on playing (a sender and receiver)

`rodio` has a `sleep_until_end` method on `Sink` that you can use to block the playing thread. The playing and the main thread both require access to the same `Sink`. Clearing the `Sink` on the main thread would cause the player thread to finish. You'll probably want the player thread to loop and block both on playing and on waiting for a message from the main thread. The main thread would set up the other 2 and you'll want 2 channels which involve messages flowing in the following ways:
- user input > main
- player > main
- main > player

I would use an enum rather than strings to model your message types.

I hope this is of some help.

**Comment by mavenried** [comment]
This is quite the grave issue. Should be a few hours work. (Yup, I'm rewriting it)

**Comment by mavenried** [comment]
Polling every 10 millis is the best i have come up with so far, what do you think?
```rust
pub fn player(tx: mpsc::Sender<Command>, prx: mpsc::Receiver<PlayerCommand>) {
    let (_stream, handle) = rodio::OutputStream::try_default().unwrap();
    let sink = rodio::Sink::try_new(&handle).unwrap();
    loop {
        match prx.recv_timeout(Duration::from_millis(10)) {
            Ok(val) => match val {
                PlayerCommand::Play(song) => play(song, &sink),
                PlayerCommand::TogglePlayState => {
                    if sink.is_paused() {
                        sink.play();
                    } else {
                        sink.pause();
                    }
                }
            },
            Err(mpsc::RecvTimeoutError::Timeout) => {
                if sink.empty() {
                    tx.send(Command::Next(1)).unwrap();
                }
            }
            Err(mpsc::RecvTimeoutError::Disconnected) => {
                println!("control thread disconnected from the player thread")
            }
        }
    }
}
```

**Comment by auronandace** [comment]
That is an improvement over the previous one but you are still busy looping, just slower. Every 10 milliseconds you are hitting the `Timeout` error and making the if check. That is still 100 times a second of needless checks. The goal is to make the player thread do one of 2 things:
- block on waiting for messages (using `recv`)
- block on playing a track (using `sleep_until_end`)

Also, you seem to be making a new `Sink` inside the player function rather than making it in the main thread and passing a reference to it to a player thread. You'll want the player thread and the main thread to access to same `Sink`.

**Comment by mavenried** [comment]
A problem arises here though, how do I block a thread till the end of playback while also listening to the main threads commands?

Another thread? Won't that be too much?😔

**Comment by auronandace** [comment]
3 threads isn't too much.

Main thread needs to do the following:
- create a `Sink`
- create the input thread (give it a sender so it can send messages back to main)
- create the player thread (give it a sender to send messages back to main and give it a receiver so it can receive messages from main, also give it a reference to the `Sink` created in main)
- loop and block on receiving messages

User input thread is super simple. Keep it like you did, a loop blocking on user input that sends to the main thread.

The player thread then needs to do the following:
- loop blocking on messages from main thread
- when playing a track use `sleep_until_end` on the `Sink` (this is what blocks the thread until the `Sink` is finished playing). After the `sleep_until_end` instruction you send a next message to main.

Because your main thread has access to the same `Sink` whenever you `clear` the `Sink` from main the player thread will then be waiting for messages. You never want to use `sleep_until_end` in the main thread because you always want it waiting on messages.

That way all threads are waiting on something and no more busy loop:
- main thread waits on user input commands from user input thread and next command from player thread
- user input thread is waiting on user input
- player thread is either busy playing a track (which can be `clear`ed from main thread) or waiting on a new message telling it to play a track from the main thread
